### ISSUE TITLE
编译报错 node v20.11.0 v16.20.2

### ISSUE THREAD

**Issue by marklove5102** [yj-liuzepeng/bookmarks-box#1]
`````
root@23bf0c3eac28:/bookmarks-box# yarn run build
yarn run v1.22.19
$ zx ./build.mjs
major
Current verion: null
Release type? Press Tab twice for suggestion 
major
Release verion? null
$ sed -i '' s/null/null/g package.json
$ tsc && vite build
sed: can't read s/null/null/g: No such file or directory
file:///bookmarks-box/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

ProcessOutput [Error]: sed: can't read s/null/null/g: No such file or directory
    at file:///bookmarks-box/build.mjs:27:4
    exit code: 2 (Misuse of shell builtins)
    at ChildProcess.<anonymous> (file:///bookmarks-box/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:301:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 2,
  _signal: null,
  _stdout: '',
  _stderr: "sed: can't read s/null/null/g: No such file or directory\n",
  _combined: "sed: can't read s/null/null/g: No such file or directory\n"
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@23bf0c3eac28:/bookmarks-box# ls
LICENSE  README.md  bookmarks-box.zip  build.mjs  index.html  node_modules  nodemon.json  package.json	public	src  tsconfig.json  tsconfig.node.json	utils  vite.config.ts  yarn.lock
root@23bf0c3eac28:/bookmarks-box# n^C^C 
root@23bf0c3eac28:/bookmarks-box# npm install  --registry=https://registry.npmmirror.com
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^null" of package "pinyin-match@^null": Tags may not have any characters that encodeURIComponent encodes.
`````

**Comment by yj-liuzepeng** [comment]
> ```
> root@23bf0c3eac28:/bookmarks-box# yarn run build
> yarn run v1.22.19
> $ zx ./build.mjs
> major
> Current verion: null
> Release type? Press Tab twice for suggestion 
> major
> Release verion? null
> $ sed -i '' s/null/null/g package.json
> $ tsc && vite build
> sed: can't read s/null/null/g: No such file or directory
> file:///bookmarks-box/node_modules/zx/build/core.js:146
>             let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
>                          ^
> 
> ProcessOutput [Error]: sed: can't read s/null/null/g: No such file or directory
>     at file:///bookmarks-box/build.mjs:27:4
>     exit code: 2 (Misuse of shell builtins)
>     at ChildProcess.<anonymous> (file:///bookmarks-box/node_modules/zx/build/core.js:146:26)
>     at ChildProcess.emit (node:events:513:28)
>     at ChildProcess.emit (node:domain:489:12)
>     at maybeClose (node:internal/child_process:1100:16)
>     at Socket.<anonymous> (node:internal/child_process:458:11)
>     at Socket.emit (node:events:513:28)
>     at Socket.emit (node:domain:489:12)
>     at Pipe.<anonymous> (node:net:301:12)
>     at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
>   _code: 2,
>   _signal: null,
>   _stdout: '',
>   _stderr: "sed: can't read s/null/null/g: No such file or directory\n",
>   _combined: "sed: can't read s/null/null/g: No such file or directory\n"
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> root@23bf0c3eac28:/bookmarks-box# ls
> LICENSE  README.md  bookmarks-box.zip  build.mjs  index.html  node_modules  nodemon.json  package.json	public	src  tsconfig.json  tsconfig.node.json	utils  vite.config.ts  yarn.lock
> root@23bf0c3eac28:/bookmarks-box# n^C^C 
> root@23bf0c3eac28:/bookmarks-box# npm install  --registry=https://registry.npmmirror.com
> npm ERR! code EINVALIDTAGNAME
> npm ERR! Invalid tag name "^null" of package "pinyin-match@^null": Tags may not have any characters that encodeURIComponent encodes.
> ```

node版本问题应该是

**Comment by yj-liuzepeng** [comment]
> ```
> root@23bf0c3eac28:/bookmarks-box# yarn run build
> yarn run v1.22.19
> $ zx ./build.mjs
> major
> Current verion: null
> Release type? Press Tab twice for suggestion 
> major
> Release verion? null
> $ sed -i '' s/null/null/g package.json
> $ tsc && vite build
> sed: can't read s/null/null/g: No such file or directory
> file:///bookmarks-box/node_modules/zx/build/core.js:146
>             let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
>                          ^
> 
> ProcessOutput [Error]: sed: can't read s/null/null/g: No such file or directory
>     at file:///bookmarks-box/build.mjs:27:4
>     exit code: 2 (Misuse of shell builtins)
>     at ChildProcess.<anonymous> (file:///bookmarks-box/node_modules/zx/build/core.js:146:26)
>     at ChildProcess.emit (node:events:513:28)
>     at ChildProcess.emit (node:domain:489:12)
>     at maybeClose (node:internal/child_process:1100:16)
>     at Socket.<anonymous> (node:internal/child_process:458:11)
>     at Socket.emit (node:events:513:28)
>     at Socket.emit (node:domain:489:12)
>     at Pipe.<anonymous> (node:net:301:12)
>     at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
>   _code: 2,
>   _signal: null,
>   _stdout: '',
>   _stderr: "sed: can't read s/null/null/g: No such file or directory\n",
>   _combined: "sed: can't read s/null/null/g: No such file or directory\n"
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> root@23bf0c3eac28:/bookmarks-box# ls
> LICENSE  README.md  bookmarks-box.zip  build.mjs  index.html  node_modules  nodemon.json  package.json	public	src  tsconfig.json  tsconfig.node.json	utils  vite.config.ts  yarn.lock
> root@23bf0c3eac28:/bookmarks-box# n^C^C 
> root@23bf0c3eac28:/bookmarks-box# npm install  --registry=https://registry.npmmirror.com
> npm ERR! code EINVALIDTAGNAME
> npm ERR! Invalid tag name "^null" of package "pinyin-match@^null": Tags may not have any characters that encodeURIComponent encodes.
> ```

试试14.几的版本，安装一下依赖试试呢

**Comment by marklove5102** [comment]
![image](https://github.com/yj-liuzepeng/bookmarks-box/assets/12666917/8d8c76fe-344a-4391-9f66-0988257844bc)
选了几个拼音版本都不行。
